plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-51
  bundler-audit:
    enabled: true
  brakeman:
    enabled: true
  scss-lint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
  - "**.bmp"
  - "**.gif"
  - "**.ico"
  - "**.jpeg"
  - "**.jpg"
  - "**.png"
  - "**.svg"
  - "db/schema.rb"
version: "2"